### ISSUE TITLE
Error while training using CORA dataset

### ISSUE THREAD

**Issue by neocsbee** [tkipf/keras-gcn#22]
Hi,

I wanted to check if the Windows 10 installation was successful using the train.py script that came with the package.

Here are the messages and the error that is shown:

\keras-gcn-master\kegra>python train.py
Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
\AppData\Roaming\Python\Python27\site-packages\theano-1.0.1+unknown-py2.7.egg\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Loading cora dataset...
Dataset has 2708 nodes, 5429 edges, 1433 features.
Using local pooling filters...
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    H = GraphConvolution(16, support, activation='relu', kernel_regularizer=l2(5e-4))([H]+G)
  File "Anaconda2\lib\site-packages\keras\engine\topology.py", line 573, in __call__
    self.assert_input_compatibility(inputs)
  File "Anaconda2\lib\site-packages\keras\engine\topology.py", line 446, in assert_input_compatibility
    str(inputs) + '. All inputs to the layer '
ValueError: Layer graph_convolution_1 was called with an input that isn't a symbolic tensor. Received type: <class 'theano.sparse.basic.SparseVariable'>. Full input: [if{}.0, SparseVariable{csr,float32}]. All inputs to the layer should be tensors.

Thanks.

**Comment by tkipf** [comment]
I think the Theano backend is broken. You might want to test this with a TensorFlow backend?

**Comment by neocsbee** [comment]
I have limited privileges to install and test TensorFlow. I initially tried with CNTK and ended up with some error there too (See: https://github.com/Microsoft/CNTK/issues/2900).

**Comment by svakulenk0** [comment]
works with TensorFlow. thank you!
