### ISSUE TITLE
Error converting string to float in train.py

### ISSUE THREAD

**Issue by sagarsamtani07** [tkipf/keras-gcn#7]
Ran into the following issue when running the train.py file. I am using python 3.4.2 and Keras 1.1.0

`Using Theano backend.
Loading cora dataset...
Traceback (most recent call last):
  File "C:/Users/sagars/PycharmProjects/GCN/kegra/train.py", line 22, in <module>
    X, A, y = load_data(dataset=DATASET)
  File "C:\Users\sagars\PycharmProjects\GCN\kegra\utils.py", line 20, in load_data
    features = sp.csr_matrix(idx_features_labels[:, 1:-2], dtype=np.float32)
  File "C:\Python34\lib\site-packages\scipy\sparse\compressed.py", line 69, in __init__
    self._set_self(self.__class__(coo_matrix(arg1, dtype=dtype)))
  File "C:\Python34\lib\site-packages\scipy\sparse\coo.py", line 204, in __init__
    self.data = self.data.astype(dtype)
ValueError: could not convert string to float: "b'0'"`

**Comment by tkipf** [comment]
Thanks for reporting. This is now fixed with https://github.com/tkipf/keras-gcn/commit/791667dc4cd197d9877db30031a129c4a838e1e3
