### ISSUE TITLE
Positional offsets argument error in train.py file

### ISSUE THREAD

**Issue by sagarsamtani07** [tkipf/keras-gcn#8]
Running the train.py file using Python 3.4.2 yielded the following error

`Using Theano backend.
Loading cora dataset...
Dataset has 2708 nodes, 5429 edges, 1432 features.
Using local pooling filters...
Traceback (most recent call last):
  File "C:/Users/sagars/PycharmProjects/GCN/kegra/train.py", line 31, in <module>
    A_ = preprocess_adj(A, SYM_NORM)
  File "C:\Users\sagars\PycharmProjects\GCN\kegra\utils.py", line 52, in preprocess_adj
    adj = normalize_adj(adj, symmetric)
  File "C:\Users\sagars\PycharmProjects\GCN\kegra\utils.py", line 42, in normalize_adj
    d = sp.diags(np.power(np.array(adj.sum(1)), -0.5).flatten())
TypeError: diags() missing 1 required positional argument: 'offsets'`

**Comment by tkipf** [comment]
Thanks. Should be fixed now: https://github.com/tkipf/keras-gcn/commit/26859f5b11423fca8a5d9e99b2165cc7fb9b2521
